version: '3'
services:
  zookeeper:
    container_name: kafka-cluster-zookeeper
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: on-failure:5
    ports:
      - "2181:2181"
    networks:
      - kafka-network
  kafka1:
    container_name: kafka-cluster-broker-app-1
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,EXTERNAL://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: on-failure:5
    ports:
      - "29092:29092"
    networks:
      - kafka-network
  kafka2:
    container_name: kafka-cluster-broker-app-2
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,EXTERNAL://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093,EXTERNAL://kafka2:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: on-failure:5
    ports:
      - "29093:29093"
  kafka3:
    container_name: kafka-cluster-broker-app-3
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094,EXTERNAL://0.0.0.0:29094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094,EXTERNAL://kafka3:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: on-failure:5
    ports:
      - "29094:29094"
    networks:
      - kafka-network
  app-replica-1:
    image: 'kafka-app:latest'
    container_name: app-replica-1
    build:
      context: ../
    restart: on-failure:5
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
    environment:
      BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9093,kafka3:9094
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - kafka-network
  app-replica-2:
    image: 'kafka-app:latest'
    container_name: app-replica-2
    build:
      context: ../
    restart: on-failure:5
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
    environment:
      BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9093,kafka3:9094
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - kafka-network
networks:
  kafka-network: